<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getAudit, mergeAnimals, removeDuplicateEvent } from '../api/audit'
const router = useRouter(); const audit = ref<any>(null); const status = ref(''); const busy = ref(false)
async function load() { busy.value = true; status.value = ''; try { audit.value = await getAudit() } catch (error) { status.value = error instanceof Error ? error.message : 'Audit could not load.' } finally { busy.value = false } }
function label(animal: any) { return animal.barnName || animal.registeredName || `Animal #${animal.animalId}` }
async function merge(finding: any, keep: any, remove: any) {
  if (!window.confirm(`Keep ${label(keep)} (#${keep.animalId}) and merge everything from ${label(remove)} (#${remove.animalId}) into it?\n\nThe second card will be removed after its history, imports, photos, pedigree links, embryos, and events are moved.`)) return
  busy.value = true; try { await mergeAnimals(keep.animalId, remove.animalId); status.value = `Merged ${label(remove)} into ${label(keep)}.`; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'Merge failed; nothing was changed.' } finally { busy.value = false }
}
async function removeEvent(finding: any, eventId: number) {
  if (!window.confirm(`Remove duplicate ${finding.eventType} event #${eventId} for ${finding.animalName}? The other event will be kept.`)) return
  busy.value = true; try { await removeDuplicateEvent(finding.eventType, eventId); status.value = 'Duplicate event removed.'; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'Event was not removed.' } finally { busy.value = false }
}
onMounted(load)
</script>
<template><main class="audit-page"><header><button @click="router.push('/reports')">← Reports</button><div><small>VENTURE DATA OFFICIAL REVIEW</small><h1>Audit Center</h1><p>Possible duplicates are suggestions only. Nothing is changed until you confirm it.</p></div><button :disabled="busy" @click="load">{{ busy ? 'Scanning…' : 'Run Audit' }}</button></header><p v-if="status" class="status">{{ status }}</p><section class="scoreboard"><article><strong>{{ audit?.animalFindings?.length ?? 0 }}</strong><span>Possible duplicate animals</span></article><article><strong>{{ audit?.eventFindings?.length ?? 0 }}</strong><span>Duplicate event groups</span></article></section><section class="panel"><h2>Possible Duplicate Animals</h2><p>Compare both cards, then choose which card survives. The merge moves linked history before removing the extra card.</p><div v-if="!audit?.animalFindings?.length" class="clear">✓ No possible duplicate animals found.</div><article v-for="(finding, index) in audit?.animalFindings ?? []" :key="index" class="finding"><div class="reasons"><b>Why flagged</b><span v-for="reason in finding.reasons" :key="reason">{{ reason }}</span></div><div class="animal-compare"><div v-for="animal in [finding.left, finding.right]" :key="animal.animalId" class="animal-card"><button class="animal-name" @click="router.push(`/animals/${animal.animalId}`)">{{ label(animal) }}</button><small>Card #{{ animal.animalId }}</small><dl><dt>Registered</dt><dd>{{ animal.registeredName || '—' }}</dd><dt>ID</dt><dd>{{ animal.registrationNumber || '—' }}</dd><dt>Born</dt><dd>{{ animal.birthDate || '—' }}</dd><dt>Dam</dt><dd>{{ animal.damName || '—' }}</dd><dt>Sire</dt><dd>{{ animal.sireName || '—' }}</dd></dl><button class="keep" :disabled="busy" @click="merge(finding, animal, animal === finding.left ? finding.right : finding.left)">Keep this card &amp; merge other</button></div></div></article></section><section class="panel"><h2>Possible Duplicate Events</h2><p>Events are grouped only when the animal and identifying date/details match.</p><div v-if="!audit?.eventFindings?.length" class="clear">✓ No duplicate event groups found.</div><article v-for="finding in audit?.eventFindings ?? []" :key="`${finding.eventType}-${finding.animalId}-${finding.signature}`" class="event-row"><div><strong>{{ finding.animalName }}</strong><span>{{ finding.eventType }} · {{ finding.signature }} · {{ finding.count }} copies</span></div><div><button @click="router.push(`/animals/${finding.animalId}`)">Review animal</button><button v-for="eventId in finding.eventIds.slice(1)" :key="eventId" class="remove" :disabled="busy" @click="removeEvent(finding, eventId)">Remove extra #{{ eventId }}</button></div></article></section></main></template>
<style scoped>.audit-page{max-width:1120px;margin:auto;min-height:100vh;padding:16px;background:#eef0f2;color:#17191e}header{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:20px;background:#17191e;border-bottom:5px solid #d8202d;color:#fff}header h1{margin:2px 0;font-style:italic;text-transform:uppercase}header p{margin:0;color:#d7d9dc}header small{color:#ff6b73;font-weight:900;letter-spacing:.12em}button{min-height:42px;border:1px solid #c9cdd2;border-radius:6px;background:#fff;padding:7px 12px;font-weight:850;cursor:pointer}.status{padding:10px;background:#fff;border-left:4px solid #d8202d}.scoreboard{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.scoreboard article{display:flex;align-items:center;gap:12px;padding:15px;background:#25282f;color:#fff}.scoreboard strong{font-size:2rem;color:#ff5964}.panel{margin:12px 0;padding:16px;background:#fff;border-top:4px solid #d8202d}.panel h2{margin-top:0}.clear{padding:20px;background:#edf9f0;color:#17602b;text-align:center;font-weight:850}.finding{margin:12px 0;padding:12px;border:1px solid #d8dbe0}.reasons{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.reasons span{padding:4px 8px;border-radius:999px;background:#fff0f1;color:#9d1721;font-size:.78rem}.animal-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px}.animal-card{padding:12px;background:#f6f7f8}.animal-name{border:0;background:transparent;color:#a91420;padding:0;font-size:1.05rem}.animal-card>small{display:block;color:#6b7280}.animal-card dl{display:grid;grid-template-columns:auto 1fr;gap:4px 9px;font-size:.82rem}.animal-card dt{font-weight:850}.animal-card dd{margin:0}.keep{width:100%;background:#d8202d;color:#fff;border:0}.event-row{display:flex;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid #ddd}.event-row>div{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.event-row span{color:#667085}.event-row .remove{background:#fff0f1;color:#9d1721;border-color:#efb5ba}@media(max-width:650px){header{grid-template-columns:1fr}header>button{width:100%}.scoreboard,.animal-compare{grid-template-columns:1fr}.event-row{align-items:stretch;flex-direction:column}.event-row>div:last-child{display:grid}.panel{padding:11px}}</style>
