<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { acceptPcdartDifference, acceptSireSuggestion, getAudit, mergeAnimals, removeDuplicateEvent } from '../api/audit'
const router = useRouter(); const audit = ref<any>(null); const status = ref(''); const busy = ref(false)
const ignoredKey = 'venture-herd-audit-correct-v1'
const ignored = ref<Set<string>>(new Set(JSON.parse(localStorage.getItem(ignoredKey) || '[]')))
function markCorrect(key: string) { if (!window.confirm('Mark this finding as correct and hide it from future audits on this device?')) return; ignored.value = new Set([...ignored.value,key]); localStorage.setItem(ignoredKey, JSON.stringify([...ignored.value])); status.value = 'Finding marked correct and hidden.' }
function isIgnored(key: string) { return ignored.value.has(key) }
function animalFindingKey(finding: any) { return `animals:${[finding.left.animalId,finding.right.animalId].sort((a,b)=>a-b).join('-')}` }
function eventFindingKey(finding: any) { return `event:${finding.eventType}:${[...finding.eventIds].sort((a:number,b:number)=>a-b).join('-')}` }
async function load() { busy.value = true; status.value = ''; try { audit.value = await getAudit() } catch (error) { status.value = error instanceof Error ? error.message : 'Audit could not load.' } finally { busy.value = false } }
function label(animal: any) { return animal.barnName || animal.registeredName || `Animal #${animal.animalId}` }
function fieldLabel(key: string) { return key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/Id$/, ' ID') }
function fieldValue(value: any) { if (value == null || value === '') return '—'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(value)) return new Date(value).toLocaleString(); return String(value) }
async function merge(finding: any, keep: any, remove: any) { if (!window.confirm(`Keep ${label(keep)} (#${keep.animalId}) and merge everything from ${label(remove)} (#${remove.animalId}) into it?`)) return; busy.value = true; try { await mergeAnimals(keep.animalId, remove.animalId); status.value = `Merged ${label(remove)} into ${label(keep)}.`; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'Merge failed; nothing was changed.' } finally { busy.value = false } }
async function removeEvent(finding: any, eventId: number) { if (!window.confirm(`Remove possible duplicate ${finding.eventType} event #${eventId} for ${finding.animalName}?`)) return; busy.value = true; try { await removeDuplicateEvent(finding.eventType, eventId); status.value = 'Duplicate event removed.'; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'Event was not removed.' } finally { busy.value = false } }
async function usePcdart(finding: any, field: 'birthdate' | 'registration' | 'calvingdate') { if (!window.confirm(`Use the PC-DART ${field.replace('date',' date')} for ${finding.animalName}?`)) return; busy.value = true; try { await acceptPcdartDifference(finding.animalId, field); status.value = `PC-DART value accepted for ${finding.animalName}.`; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'PC-DART value was not applied.' } finally { busy.value = false } }
async function useSuggestedSire(animal: any) { if (!window.confirm(`Set ${animal.suggestedSire} as ${label(animal)}'s sire? Verify the registered name before accepting.`)) return; busy.value = true; try { await acceptSireSuggestion(animal.animalId); status.value = `${animal.suggestedSire} saved as ${label(animal)}'s sire.`; await load() } catch (error) { status.value = error instanceof Error ? error.message : 'Suggested sire was not saved.' } finally { busy.value = false } }
onMounted(load)
</script>

<template><main class="audit-page">
  <header><button @click="router.push('/reports')">← Reports</button><div><small>VENTURE DATA OFFICIAL REVIEW</small><h1>Audit Center</h1><p>Possible errors are suggestions only. Nothing changes until you confirm it.</p></div><button :disabled="busy" @click="load">{{ busy ? 'Scanning…' : 'Run Audit' }}</button></header>
  <p v-if="status" class="status">{{ status }}</p>
  <section class="scoreboard"><article><strong>{{ audit?.animalFindings?.length ?? 0 }}</strong><span>Possible duplicate animals</span></article><article><strong>{{ audit?.eventFindings?.length ?? 0 }}</strong><span>Event timing findings</span></article><article><strong>{{ (audit?.birthDateFindings?.length ?? 0) + (audit?.registrationFindings?.length ?? 0) + (audit?.calvingDateFindings?.length ?? 0) }}</strong><span>PC-DART differences</span></article></section>
  <section class="panel"><h2>Missing Sire Information</h2><p>These active females need a confirmed sire for pedigree and milk-sire analytics. Suggestions come from the word immediately before the cow-name portion of the registered name—review before accepting.</p><div v-if="!audit?.missingSireFindings?.length" class="clear">✓ All active females have a sire recorded.</div><div class="missing-grid"><article v-for="animal in audit?.missingSireFindings ?? []" v-show="!isIgnored(`missing-sire:${animal.animalId}`)" :key="animal.animalId"><div><strong>{{ label(animal) }}</strong><small>Card #{{ animal.animalId }} · {{ animal.registeredName || 'No registered name' }}</small><b v-if="animal.suggestedSire" class="sire-suggestion">Suggested sire: {{ animal.suggestedSire }}</b></div><div class="audit-actions"><button v-if="animal.suggestedSire" @click="useSuggestedSire(animal)">Accept {{ animal.suggestedSire }}</button><button @click="router.push(`/animals/${animal.animalId}`)">Open cow</button><button class="ignore" @click="markCorrect(`missing-sire:${animal.animalId}`)">No sire known · ignore</button></div></article></div></section>
  <section class="panel"><h2>Possible Duplicate Animals</h2><p>Compare both cards, then choose which card survives.</p><div v-if="!audit?.animalFindings?.length" class="clear">✓ No possible duplicate animals found.</div><article v-for="(finding,index) in audit?.animalFindings ?? []" v-show="!isIgnored(animalFindingKey(finding))" :key="index" class="finding"><div class="reasons"><b>Why flagged</b><span v-for="reason in finding.reasons" :key="reason">{{ reason }}</span><button class="ignore" @click="markCorrect(animalFindingKey(finding))">These cards are correct · ignore</button></div><div class="compare"><div v-for="animal in [finding.left,finding.right]" :key="animal.animalId" class="animal-card"><button class="name" @click="router.push(`/animals/${animal.animalId}`)">{{ label(animal) }}</button><small>Card #{{ animal.animalId }}</small><dl><dt>Registered</dt><dd>{{ animal.registeredName || '—' }}</dd><dt>ID</dt><dd>{{ animal.registrationNumber || '—' }}</dd><dt>Born</dt><dd>{{ animal.birthDate || '—' }}</dd><dt>Dam</dt><dd>{{ animal.damName || '—' }}</dd><dt>Sire</dt><dd>{{ animal.sireName || '—' }}</dd></dl><button class="keep" :disabled="busy" @click="merge(finding,animal,animal===finding.left?finding.right:finding.left)">Keep this card &amp; merge other</button></div></div></article></section>
  <section class="panel"><h2>Possible Duplicate or Mistimed Events</h2><p><b>Same animal only:</b> events belonging to different cows are never compared.</p><div v-if="!audit?.eventFindings?.length" class="clear">✓ No suspiciously close events found.</div><article v-for="finding in audit?.eventFindings ?? []" v-show="!isIgnored(eventFindingKey(finding))" :key="`${finding.eventType}-${finding.animalId}-${finding.signature}`" class="finding"><div class="event-head"><div><b>{{ finding.animalName }}</b><p>{{ finding.reviewReason }} · {{ finding.eventType }} · {{ finding.signature }}</p></div><div class="audit-actions"><button @click="router.push(`/animals/${finding.animalId}`)">Open animal card</button><button class="ignore" @click="markCorrect(eventFindingKey(finding))">Both are correct · ignore</button></div></div><div class="compare"><article v-for="(record,i) in finding.records" :key="finding.eventIds[i]" class="animal-card"><h3>Record {{ i+1 }} · #{{ finding.eventIds[i] }}</h3><dl><template v-for="(value,key) in record" :key="key"><dt>{{ fieldLabel(String(key)) }}</dt><dd>{{ fieldValue(value) }}</dd></template></dl><button class="keep" :disabled="busy" @click="removeEvent(finding,finding.eventIds[i===0?1:0])">Keep this record &amp; remove other</button></article></div></article></section>
  <section class="panel"><h2>Birth Date &amp; Age Differences</h2><p>Exact imported dates are compared directly. When PC-DART supplies only years-months, the audit compares that reported age with the age calculated from the cow card on the report date.</p><div v-if="!audit?.birthDateFindings?.length" class="clear">✓ No imported birth-date or age differences found.</div><div class="missing-grid"><article v-for="finding in audit?.birthDateFindings ?? []" v-show="!isIgnored(`birth-date:${finding.animalId}:${finding.importedBirthDate || finding.importedAge}`)" :key="`${finding.animalId}-${finding.importedBirthDate || finding.importedAge}`"><div><strong>{{ finding.animalName }}</strong><small v-if="finding.importedBirthDate">Card date: {{ finding.currentBirthDate || 'missing' }} · {{ finding.source }} date: {{ finding.importedBirthDate }}</small><small v-else>Card calculates {{ finding.currentAgeAtReport }} · PC-DART reports {{ finding.importedAge }} on {{ finding.reportDate }}</small></div><span class="audit-actions"><button v-if="finding.importedBirthDate" @click="usePcdart(finding,'birthdate')">Use PC-DART</button><button class="ignore" @click="markCorrect(`birth-date:${finding.animalId}:${finding.importedBirthDate || finding.importedAge}`)">Keep app value</button><button @click="router.push(`/animals/${finding.animalId}`)">Open card</button></span></article></div></section>
  <section class="panel"><h2>PC-DART Registration / DHI ID Differences</h2><p>Compares the cow card ID with the latest usable PC-DART DHI ID. Barn names accidentally supplied as IDs are ignored.</p><div v-if="!audit?.registrationFindings?.length" class="clear">✓ Registration and DHI IDs agree.</div><div class="missing-grid"><article v-for="finding in audit?.registrationFindings ?? []" v-show="!isIgnored(`pcdart-id:${finding.animalId}:${finding.pcdartRegistrationId}`)" :key="`id-${finding.animalId}`"><div><strong>{{ finding.animalName }}</strong><small>App card: {{ finding.cardRegistrationId || 'missing' }} · PC-DART: {{ finding.pcdartRegistrationId }} · report {{ finding.reportDate }}</small></div><div class="audit-actions"><button @click="usePcdart(finding,'registration')">Use PC-DART</button><button class="ignore" @click="markCorrect(`pcdart-id:${finding.animalId}:${finding.pcdartRegistrationId}`)">Keep app value</button><button @click="router.push(`/animals/${finding.animalId}`)">Open card</button></div></article></div></section>
  <section class="panel"><h2>PC-DART Calving Date Differences</h2><p>Compares each cow's latest calving event in the app with the latest calving date imported from PC-DART. Different cows are never compared.</p><div v-if="!audit?.calvingDateFindings?.length" class="clear">✓ Stored calving dates agree with PC-DART.</div><div class="missing-grid"><article v-for="finding in audit?.calvingDateFindings ?? []" v-show="!isIgnored(`pcdart-calving:${finding.animalId}:${finding.pcdartCalvingDate}`)" :key="`calving-${finding.animalId}`"><div><strong>{{ finding.animalName }}</strong><small>App event: {{ finding.appCalvingDate || 'missing' }} · PC-DART: {{ finding.pcdartCalvingDate }} · report {{ finding.reportDate }}</small></div><div class="audit-actions"><button @click="usePcdart(finding,'calvingdate')">Use PC-DART</button><button class="ignore" @click="markCorrect(`pcdart-calving:${finding.animalId}:${finding.pcdartCalvingDate}`)">Keep app value</button><button @click="router.push(`/animals/${finding.animalId}`)">Open card</button></div></article></div></section>
</main></template>

<style scoped>
.audit-actions{display:flex;gap:7px;flex-wrap:wrap}.ignore{border:2px solid #31572c!important;background:#edf9f0!important;color:#174b27!important}
.audit-page{max-width:1120px;margin:auto;min-height:100vh;padding:16px;background:#eef0f2;color:#17191e}header{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:20px;background:#17191e;border-bottom:5px solid #d8202d;color:#fff}header h1{margin:2px 0}header p{margin:0;color:#d7d9dc}header small{color:#ff6b73;font-weight:900}button{min-height:42px;border:1px solid #c9cdd2;border-radius:6px;background:#fff;padding:7px 12px;font-weight:850;cursor:pointer}.status,.panel{margin:12px 0;padding:16px;background:#fff;border-top:4px solid #d8202d}.scoreboard{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.scoreboard article{display:flex;align-items:center;gap:12px;padding:15px;background:#25282f;color:#fff}.scoreboard strong{font-size:2rem;color:#ff5964}.clear{padding:20px;background:#edf9f0;color:#17602b;text-align:center;font-weight:850}.missing-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.missing-grid article,.event-head{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px;background:#f6f7f8}.missing-grid div{display:grid}.missing-grid small{color:#667085}.finding{margin:12px 0;padding:12px;border:1px solid #d8dbe0}.reasons{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.reasons span{padding:4px 8px;border-radius:999px;background:#fff0f1;color:#9d1721}.compare{display:grid;grid-template-columns:1fr 1fr;gap:10px}.animal-card{padding:12px;background:#f6f7f8}.name{border:0;background:transparent;color:#a91420;padding:0;font-size:1.05rem}.animal-card dl{display:grid;grid-template-columns:auto 1fr;gap:4px 9px;font-size:.82rem}.animal-card dd{margin:0}.keep{width:100%;background:#d8202d;color:#fff;border:0}.event-head p{margin:5px 0;color:#667085}@media(max-width:650px){header,.scoreboard,.missing-grid,.compare{grid-template-columns:1fr}.event-head{align-items:stretch;flex-direction:column}}
</style>
